<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWindowsForms>true</UseWindowsForms>
        <ApplicationIcon>app.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <Compile Update="PresetNameForm.cs">
        <SubType>Form</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AliHaFFMPEG.Core\AliHaFFMPEG.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="app.ico">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
